# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-28 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idarquivo', models.CharField(max_length=512)),
                ('req', models.CharField(max_length=512)),
                ('wo', models.CharField(max_length=512)),
                ('datahorageracaoarquivo', models.CharField(max_length=512)),
                ('data_agendamento', models.CharField(blank=True, max_length=512, null=True)),
                ('descricao', models.TextField()),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Aceito'), (2, 'Recuso'), (3, 'Pendente'), (1, 'Atualizacao'), (4, 'Cancelado'), (5, 'Resolvido'), (2, 'Agendamento')], null=True)),
                ('contato_agendamento', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
